### ISSUE TITLE
3 Predecessors

### ISSUE THREAD

**Issue by adamsocrat** [cppcoders/critical-path-method-python#1]
If user insert three "pr" like this.
A,-,12
B,-,9
C,A,10
D,B,10
E,B,24
F,A,10
G,C,35
H,D,40
I,A,15
**J,EGH,4**
**K,FIJ,6**

repo gives:
```
A B C D E F I G H J L K Traceback (most recent call last):
  File "C:\Users\Yunus\PycharmProjects\scientific\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-fcc47e65dd13>", line 1, in <module>
    runfile('C:/Users/Yunus/PycharmProjects/scientific/cpm-python/main.py', wdir='C:/Users/Yunus/PycharmProjects/scientific/cpm-python')
  File "C:\Users\Yunus\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\203.7717.65\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\Yunus\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\203.7717.65\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Yunus/PycharmProjects/scientific/cpm-python/main.py", line 85, in <module>
    ls.append(atts[ord(data.iloc[s, 1][k]) - 65]["EF"])
KeyError: 'EF'
```

**Comment by adamsocrat** [comment]
Because of no further investigation I'm closing the issue.
