### ISSUE TITLE
pygraphviz not installing

### ISSUE THREAD

**Issue by tanbin-hasnat-shehab** [cppcoders/critical-path-method-python#2]
Path
A B C D E F G H I 
------------------------
{'Name': 'A', 'DU': 7, 'ES': 0, 'EF': 7, 'LF': 7, 'LS': 0, 'SK': 0}
{'Name': 'B', 'DU': 9, 'ES': 7, 'EF': 16, 'LF': 16, 'LS': 7, 'SK': 0}
{'Name': 'C', 'DU': 3, 'ES': 7, 'EF': 10, 'LF': 19, 'LS': 16, 'SK': 9}
{'Name': 'D', 'DU': 8, 'ES': 16, 'EF': 24, 'LF': 24, 'LS': 16, 'SK': 0}
{'Name': 'E', 'DU': 5, 'ES': 10, 'EF': 15, 'LF': 24, 'LS': 19, 'SK': 9}
{'Name': 'F', 'DU': 4, 'ES': 10, 'EF': 14, 'LF': 24, 'LS': 20, 'SK': 10}
{'Name': 'G', 'DU': 2, 'ES': 24, 'EF': 26, 'LF': 26, 'LS': 24, 'SK': 0}
{'Name': 'H', 'DU': 1, 'ES': 26, 'EF': 27, 'LF': 27, 'LS': 26, 'SK': 0}
{'Name': 'End', 'DU': 0, 'ES': 27, 'EF': 27, 'LF': 27, 'LS': 27, 'SK': 0}

Traceback (most recent call last):
  File "C:\Users\shehab\AppData\Local\Programs\Python\Python39\lib\site-packages\networkx\drawing\nx_agraph.py", line 281, in pygraphviz_layout
    import pygraphviz
ModuleNotFoundError: No module named 'pygraphviz'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\DRIVE\pythons\frame\alpha\2D FRAME\cpm-python-master\main.py", line 127, in <module>
    pos = nx.nx_agraph.graphviz_layout(G2, prog='dot')
  File "C:\Users\shehab\AppData\Local\Programs\Python\Python39\lib\site-packages\networkx\drawing\nx_agraph.py", line 239, in graphviz_layout
    return pygraphviz_layout(G, prog=prog, root=root, args=args)
  File "C:\Users\shehab\AppData\Local\Programs\Python\Python39\lib\site-packages\networkx\drawing\nx_agraph.py", line 283, in pygraphviz_layout
    raise ImportError("requires pygraphviz " "http://pygraphviz.github.io/") from e
ImportError: requires pygraphviz http://pygraphviz.github.io/

***Repl Closed***

**Comment by Npurnomo** [comment]
if you use conda, you can install with the following : https://anaconda.org/conda-forge/pygraphviz
