### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'.

### ISSUE THREAD

**Issue by bezborodow** [cppcoders/critical-path-method-python#3]
It appears that `DataFrame.append` has been deprecated in pandas version 2.0.

Version:

```
  Downloading pandas-2.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
```

Traceback:

```
Traceback (most recent call last):
  File "/home/dbezborodov/src/cpm-python/main.py", line 30, in <module>
    data = data.append(df)
           ^^^^^^^^^^^
  File "/home/dbezborodov/src/cpm-python/venv/lib64/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

```

**Comment by bezborodow** [comment]
After downgrading, the following message appears:

```
/home/dbezborodov/src/cpm-python/main.py:30: FutureWarning: The frame.append method is
deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
```

**Comment by joloevaa** [comment]
My solution to this issue was:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
#import pygraphviz

for q in range(1, 10):
    start = []
    graph = []
    atts = []
    path = []
    new = []
    st = ""
    data = pd.read_csv(f"data/data{q}.csv")
    last = data.iloc[-1, 0]
    last = chr(ord(last) + 1)

    for j in range(len(data)):
        for k in range(len(data.iloc[j, 1])):
            if data.iloc[j, 1][k] != '-':
                new.append(data.iloc[j, 1][k])

    for j in range(len(data)):
        if not data.iloc[j, 0] in new:
            st = st + data.iloc[j, 0]

    if data.shape[1] == 3:
        df = pd.DataFrame([[last, st, 0]], columns=["ac", "pr", "du"])
    else:
        df = pd.DataFrame([[last, st, 0, 0, 0]], columns=["ac", "pr", "b", "m", "a"])

    # Using pd.concat for appending new DataFrame rows
    data = pd.concat([data, df], ignore_index=True)

    for i in range(len(data)):
        graph.append([])
        atts.append({})

    for j in range(len(data)):
        atts[j]["Name"] = data.iloc[j, 0]
        if data.shape[1] == 3:
            atts[j]["DU"] = data.iloc[j, 2]
        else:
            atts[j]["DU"] = (data.iloc[j, 4] + 4 * data.iloc[j, 3] + data.iloc[j, 2]) / 6
        if data.iloc[j, 1] == "-":
            start.append(ord(data.iloc[j, 0]) - 65)
            continue
        for k in range(len(data.iloc[j, 1])):
            graph[ord(data.iloc[j, 1][k]) - 65].append(ord(data.iloc[j, 0]) - 65)

    level = [None] * len(graph)


    def BFS(s, graph):
        visited = [False] * len(graph)
        queue = []
        for i in s:
            queue.append(i)
            level[i] = 0
            visited[i] = True
        while queue:
            s = queue.pop(0)
            path.append(s)
            for i in graph[s]:
                if not visited[i]:
                    queue.append(i)
                    level[i] = level[s] + 1
                    visited[i] = True
                else:
                    level[i] = max(level[s] + 1, level[i])


    BFS(start, graph)

    levels = [None] * len(path)
    for i in range(len(path)):
        levels[i] = level[path[i]]
    path = [x for y, x in sorted(zip(levels, path))]
    print("\nPath")
    for i in path:
        print(chr(i + 65), end=' ')

    for s in path:
        if data.iloc[s, 1] == "-":
            atts[s]["ES"] = 0
        else:
            ls = [atts[ord(data.iloc[s, 1][k]) - 65]["EF"] for k in range(len(data.iloc[s, 1]))]
            atts[s]["ES"] = max(ls)
        atts[s]["EF"] = atts[s]["DU"] + atts[s]["ES"]

    for i in range(len(graph)):
        if not graph[i]:
            atts[i]["LF"] = atts[i]["EF"]
            atts[i]["LS"] = atts[i]["ES"]

    print("\n------------------------")
    path.reverse()
    for i in path:
        if data.iloc[i, 1] != "-":
            for k in range(len(data.iloc[i, 1])):
                if "LF" in atts[ord(data.iloc[i, 1][k]) - 65].keys():
                    atts[ord(data.iloc[i, 1][k]) - 65]["LF"] = min(atts[i]["LS"],
                                                                   atts[ord(data.iloc[i, 1][k]) - 65]["LF"])
                else:
                    atts[ord(data.iloc[i, 1][k]) - 65]["LF"] = atts[i]["LS"]
                atts[ord(data.iloc[i, 1][k]) - 65]["LS"] = atts[ord(data.iloc[i, 1][k]) - 65]["LF"] - \
                                                           atts[ord(data.iloc[i, 1][k]) - 65]["DU"]
        atts[i]["SK"] = atts[i]["LF"] - atts[i]["EF"]

    atts[-1]["Name"] = "End"
    for j in range(len(graph)):
        print(atts[j])

    G2 = nx.DiGraph()
    for i in range(len(graph)):
        for j in graph[i]:
            G2.add_edge(atts[i]["Name"], atts[j]["Name"])
    temp = dict(zip([atts[i]["Name"] for i in range(len(atts))], atts))
    nx.set_node_attributes(G2, temp)
    fig, ax = plt.subplots(figsize=(15, 15))
    #pos = nx.nx_agraph.graphviz_layout(G2, prog='dot')
    pos = nx.spring_layout(G2)
    nx.draw_networkx_edges(G2, pos, edge_color='olive', width=1, arrowstyle='simple', arrowsize=20,
                           min_source_margin=25, min_target_margin=25)
    crt = [j for j, i in temp.items() if i["LF"] == i["EF"]]
    notcrt = [j for j, i in temp.items() if i["LF"] != i["EF"]]
    nx.draw_networkx_nodes(G2, pos, node_size=2000, node_color='seagreen', ax=ax, nodelist=crt)
    nx.draw_networkx_nodes(G2, pos, node_size=1000, node_color='wheat', ax=ax, nodelist=notcrt)
    nx.draw_networkx_labels(G2, pos, ax=ax, font_weight="bold", font_color="black", font_size=16)


    def without(d, keys={"Name"}):
        return {x: d[x] for x in d if x not in keys}


    for node in G2.nodes:
        xy = pos[node]
        d = without(G2.nodes[node])
        text = '\n'.join(f'{k}: {v}' for k, v in d.items())
        ax.annotate(text, xy=xy, xytext=(50, 5), textcoords="offset points",
                    bbox=dict(boxstyle="round", fc="lightgrey"), arrowprops=dict(arrowstyle="wedge"))
    ax.axis('off')
    plt.savefig(f'images/fig{q}.png')

**Comment by bezborodow** [comment]
https://pandas.pydata.org/pandas-docs/version/1.4/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append
